### PR TITLE
915771: Review of spanish locale and english-to-spanish translations.

### PR DESCRIPTION
**Pull request by MohanrajRKM**
### Bug description

The Spanish locale for the grid and pager components contains some incorrect translations in the "es.json" locale file.

### Root cause

Some locale keywords have been translated incorrectly in Spanish.

### Reason for not identifying earlier

Find how it was missed in our earlier testing and development by analyzing the below checklist. This will help prevent similar mistakes in the future.

- [ ] Guidelines/documents are not followed

- Common guidelines / Core team guideline

- Specification document

- Requirement document

- [x] Guidelines/documents are not given

- Common guidelines / Core team guideline

- Specification document

- Requirement document

### Reason:

Guidelines/documents are not given - Requirement document

### Action taken:

NA

### Related areas:

Locale, Grid, Pager

### Is it a breaking issue?

No

### Solution description

Reviewed and corrected the inaccurate translations in the Spanish locale for the grid and pager components by comparing them with the translators.

### Output screenshots

image
image

### Areas affected and ensured

Grid, Pager, Locale for "es.json" file.

### Additional checklist

This may vary for different teams or products. Check with your scrum masters.

- Did you run the automation against your fix? - Yes

- Is there any API name change? - No

- Is there any existing behavior change of other features due to this code change? - No

- Does your new code introduce new warnings or binding errors? - No

- Does your code pass all FxCop and StyleCop rules? a- No

- Did you record this case in the unit test or UI test? - No

### CODE REVIEW

**Review by rajapandiyan-settu — CHANGES_REQUESTED** [review]
Kindly recheck the translation text of following keywords item, items, clear, templateCell. Also share the output screenshot for all the modified keywords.

**Comment by MohanrajRKM** [comment]
I have updated the output screenshot and provided the revised words below.
Item and Items :
image
image
Clear : 
image
Template Cell :
image

**Review by rajapandiyan-settu — APPROVED** [review]
I reviewed the description and fix. Everything is fine.

**Review by jmfarook7 — APPROVED** [review]
fine

**Pull request merged**
